title: "Jonathan Z. Ong | Developmental Cognitive Neuroscience"
email: jonathanzong98@gmail.com
description: "Explore Jonathan Z. Ong’s research in developmental cognitive neuroscience, including studies on infant neurodevelopment, parent-infant interactions, and optogenetic models."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jonathanongzm.github.io/" # replace with your actual domain
twitter_username: jonathanongz
github_username: jonathanongzm

# Build settings
theme: minima
#plugins:
#  - jekyll-feed
