title: Jonathan Z. Ong
email: jonathanzong98@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jonathan Z. Ong is is a master's student in developmental cognitive neuroscience, studying parent-infant interactions at behavioral and neural levels. He integrates research in psychology and animal neuroscience with advanced data analysis to uncover patterns in early child development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jonathanongz
github_username: jonathanongzm

# Build settings
theme: minima
#plugins:
#  - jekyll-feed
